name: iteso_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connection_verify: 1.0.4
  connectivity: ^3.0.2
  jiffy: ^4.0.0
  flutter_icons: 1.1.0
  intl: ^0.17.0
  table_calendar: ^2.3.3
  url_launcher: ^6.0.2
  clip_shadow: 0.2.1
  flutter_statusbarcolor: 0.2.3
  supercharged: ^2.0.0
  http: ^0.13.0
  curved_navigation_bar: ^0.3.7
  get: ^3.26.0
  flutter:
    sdk: flutter

  floor: ^0.19.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.19.1
  build_runner: ^1.10.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/