name: iteso_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: 5.7.8
  clip_shadow: 0.2.1
  flutter_statusbarcolor: 0.2.3
  supercharged: 1.11.0
  http: 0.12.2
  curved_navigation_bar: 0.3.4
  get: 3.15.0
  flutter:
    sdk: flutter

  floor: ^0.17.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.17.0
  build_runner: ^1.10.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/